import { Activity, Aperture, BarChart3, BookOpen, Camera, Compass, Database, Flame, Globe2, Layers3, Orbit, Radio, Rocket, Satellite, ScanLine, Sparkles, Sun, Telescope, type LucideIcon } from "lucide-react";

export type Destination = { href: string; label: string; title: string; emphasis: string; description: string; source: string; sourceUrl: string; group: "Earth" | "Space" | "Discover"; icon: LucideIcon; color: string };
export const DESTINATIONS: Destination[] = [
  { href: "/dashboard", label: "Mission control", title: "A wider", emphasis: "perspective.", description: "Your starting point for a living planet and an extraordinary universe. Explore the latest available NASA observations.", source: "NASA OPEN DATA", sourceUrl: "https://api.nasa.gov/", group: "Discover", icon: Compass, color: "#9cbfff" },
  { href: "/events", label: "Natural events", title: "Our planet.", emphasis: "Always in motion.", description: "Follow wildfires, storms, volcanoes, and shifting ice through NASA’s curated Earth observations.", source: "NASA EONET · V3", sourceUrl: "https://eonet.gsfc.nasa.gov/", group: "Earth", icon: Activity, color: "#83d9c6" },
  { href: "/map", label: "Event map", title: "Every event.", emphasis: "A place on Earth.", description: "Explore natural events on an interactive world map.", source: "NASA EONET", sourceUrl: "https://eonet.gsfc.nasa.gov/", group: "Earth", icon: Globe2, color: "#83d9c6" },
  { href: "/explore", label: "3D Earth", title: "Look a little", emphasis: "closer.", description: "Orbit Earth, follow spacecraft, and explore the planet through NASA’s science observations.", source: "NASA / JPL · EARTH SCIENCE", sourceUrl: "https://eyes.nasa.gov/apps/earth/#/", group: "Earth", icon: Orbit, color: "#a1c7fb" },
  { href: "/epic", label: "Earth from space", title: "A million miles.", emphasis: "One home.", description: "Watch Earth turn through DSCOVR’s Earth Polychromatic Imaging Camera. Browse the latest available daily sequence.", source: "NASA · DSCOVR / EPIC", sourceUrl: "https://epic.gsfc.nasa.gov/", group: "Earth", icon: Camera, color: "#9ccaff" },
  { href: "/earth-imagery", label: "Satellite imagery", title: "A different", emphasis: "point of view.", description: "Explore NASA’s daily satellite imagery. Choose a place, a date, and a new perspective on the surface below.", source: "NASA GIBS · WORLDVIEW", sourceUrl: "https://www.earthdata.nasa.gov/data/tools/gibs", group: "Earth", icon: Layers3, color: "#9bd2d8" },
  { href: "/analytics", label: "Event analytics", title: "See the patterns.", emphasis: "Find the context.", description: "Explore a year of recorded natural events, their categories, and the sources behind them.", source: "NASA EONET · 365 DAYS", sourceUrl: "https://eonet.gsfc.nasa.gov/", group: "Earth", icon: BarChart3, color: "#9bd7c8" },
  { href: "/apod", label: "Picture of the day", title: "A daily dose", emphasis: "of wonder.", description: "Remarkable images. Extraordinary science. Discover the universe through NASA’s Astronomy Picture of the Day.", source: "NASA · APOD", sourceUrl: "https://apod.nasa.gov/", group: "Space", icon: Aperture, color: "#b8b2ee" },
  { href: "/mars", label: "Mars exploration", title: "Another world.", emphasis: "Within reach.", description: "Discover the landscapes, rovers, and missions revealing the story of the red planet.", source: "NASA IMAGE & VIDEO LIBRARY", sourceUrl: "https://images.nasa.gov/", group: "Space", icon: Rocket, color: "#e5b095" },
  { href: "/asteroids", label: "Near-Earth asteroids", title: "Passing through", emphasis: "our neighborhood.", description: "Compare the size, speed, and close approaches of near-Earth objects in the coming week.", source: "NASA / JPL · NEOWS", sourceUrl: "https://api.nasa.gov/#asteroids-neows", group: "Space", icon: ScanLine, color: "#ddb59a" },
  { href: "/space-weather", label: "Space weather", title: "The Sun sets", emphasis: "the scene.", description: "Explore solar flares, coronal mass ejections, and geomagnetic storms recorded by NASA’s space-weather database.", source: "NASA · DONKI", sourceUrl: "https://ccmc.gsfc.nasa.gov/tools/DONKI/", group: "Space", icon: Sun, color: "#eac187" },
  { href: "/satellites", label: "Satellite catalog", title: "Above us.", emphasis: "Around the clock.", description: "Search spacecraft and inspect their latest available orbital elements, inclination, and orbital period.", source: "TLE API · ORBITAL ELEMENTS", sourceUrl: "https://tle.ivanstanojevic.me/", group: "Space", icon: Satellite, color: "#92c8e2" },
  { href: "/fireballs", label: "Fireballs & bolides", title: "A moment of light.", emphasis: "A trail of data.", description: "Explore reported atmospheric fireballs, from radiant energy to altitude and velocity.", source: "NASA / JPL · CNEOS", sourceUrl: "https://cneos.jpl.nasa.gov/fireballs/", group: "Space", icon: Flame, color: "#e3ab95" },
  { href: "/exoplanets", label: "Exoplanet archive", title: "So many stars.", emphasis: "So many worlds.", description: "Search confirmed planets beyond our solar system. Compare their host stars, discovery methods, and physical properties.", source: "NASA EXOPLANET ARCHIVE", sourceUrl: "https://exoplanetarchive.ipac.caltech.edu/", group: "Space", icon: Sparkles, color: "#bcb0e8" },
  { href: "/media", label: "NASA media library", title: "The universe has", emphasis: "stories to tell.", description: "Explore NASA’s collection of photographs, videos, and audio. Find a moment that changes your perspective.", source: "NASA IMAGE & VIDEO LIBRARY", sourceUrl: "https://images.nasa.gov/", group: "Discover", icon: Telescope, color: "#b5bcea" },
  { href: "/techport", label: "Technology portfolio", title: "Ideas today.", emphasis: "Possibilities tomorrow.", description: "Explore the projects and research shaping NASA’s next chapter of discovery.", source: "NASA · TECHPORT", sourceUrl: "https://techport.nasa.gov/", group: "Discover", icon: Database, color: "#a5d1bf" },
  { href: "/intel", label: "Global intelligence", title: "A connected world.", emphasis: "A clearer picture.", description: "Explore news, context, and the EarthSphere tools that help you follow our changing world.", source: "EARTHSPHERE · INTELLIGENCE", sourceUrl: "https://earthsphere.in", group: "Discover", icon: Radio, color: "#b2c8da" },
  { href: "/about", label: "Our story", title: "Made on Earth.", emphasis: "For the curious.", description: "A passion for exploration. A belief in open science. A new way to see the place we call home.", source: "INDEPENDENT PLATFORM · OPEN SCIENCE", sourceUrl: "https://api.nasa.gov/", group: "Discover", icon: BookOpen, color: "#aac5eb" },
];

export function destinationFor(path: string) { return DESTINATIONS.find(item => path === item.href || path.startsWith(item.href + "/")); }
